"""empty message

Revision ID: 48aed76ce63b
Revises: 
Create Date: 2016-12-23 21:01:40.107670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48aed76ce63b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_users', sa.Column('email', sa.String(length=256), nullable=False))
    op.add_column('login_users', sa.Column('last_login_up', sa.String(length=128), nullable=True))
    op.add_column('login_users', sa.Column('password', sa.String(length=256), nullable=False))
    op.drop_column('login_users', 'last_login_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_users', sa.Column('last_login_ip', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('login_users', 'password')
    op.drop_column('login_users', 'last_login_up')
    op.drop_column('login_users', 'email')
    # ### end Alembic commands ###
